version: '3.1'
services:
  stats-server:
    build: stats/stats-server/
    image: stats
    container_name: container_stats
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/stats
      - DB_NAME=stats
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - DB_HOST=db
      - DB_PORT=5432

  stats-db:
    image: postgres:14-alpine
    container_name: stats_postgres
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123

  main-service:
    build: main-service/
    image: servermain
    container_name: container_servermain
    ports:
      - "8080:8080"
    depends_on:
      - main-db

  main-db:
    image: postgres:14-alpine
    container_name: main_postgres
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DBM=mainservice
      - POSTGRES_USERM=postgres
      - POSTGRES_PASSWORDM=123